spring:
  application:
    name: elearning
    version: @project.version@
  profiles:
    active: @spring.profiles.active@

  datasource:
    elearning:
      hikari:
        connection-test-query: SELECT 1 FROM DUAL
        minimum-idle: 1
        maximum-pool-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost/elearning_dev?serverTimezone=Asia/Kolkata&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8
      username: elearn
      password: Elearn@2024
      initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
      initialization-mode: never
    properties:
      hibernate:
        format_sql: true
        integration:
          envers:
            enabled: false

  flyway:
    table: ep_schema_history
    locations: classpath:db/migration/dev
    out-of-order: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

server:
  port: 6161
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: info,health,flyway
      base-path: /app

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html